branches:
  only:
  - master
before_script:
- docker login -u $dockerhubuser -p $dockerhubpassword docker.io
script:
- "./build.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_42ac3787701f_key -iv $encrypted_42ac3787701f_iv
  -in id_rsa.enc -out id_rsa -d
