branches:
  only:
  - master
before_script:
- docker login -u $dockerhubuser -p $dockerhubpassword docker.io
script:
- "./build.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_42ac3787701f_key -iv $encrypted_42ac3787701f_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 700 id_rsa
env:
  global:
    secure: PaF3H8PqOuY2n1w6M1P3jRcF+EYSvzwrmRGlo42iv5eJhAipfkMHxACycgH/NjinBs0BB5Jp//zZ95YegN7YmO6KteR3gZ1FjkHw71z92YHv+r9UOjeCLeos87xy5kG6gZ3iyIS0cmuhomfiaKMENzdyL8H0WkPaSFg1XO5ZR4svG/mXxXxYCpIkfw/xXRqi26uRnJjQ60+gpfx2sKTr5AdYMuVH2wXFxnzhQCrXaZqyKBqvMQvofJctldEgxztnAW5jfYwM1KnMtmf53EngANh1ljPI/dPkaZI4Ul2GGVuabdGfjR/2/P1y5R/qIDWpdBKbpexkaOOZYGijNTSkDqZePlm9/oYHjWOTHMNWLTmma8prFyDVyAV+Q3mXqOkSxR0XDbLHmkuHKAPRuSXqcuGbRHXBfslwyhWBdZXm1Tw0tIaNyIo1D4so3oDpwF+asN73MU51ZjRyEOVVLHEYbMxEwv5SDkcD+f6WsoOUPdKBUYVoA5rHhSmByTb08sKgAjkrDoDiAM0AkFO3fzGpSPLwUN+nHX6vJ8esTVLIwW2zFk/S9nVf8ABcIui5ud40Zh3GeG1eZ7Mzuueib6kF1b0gCLhBDbWeudbTlTgQqbggneCquBotTrMQZlI3tM5G0LCwQvjYHUcilb/qWAFzQCfJQKqKU1oobqo1+3VhBPI=
